cobra/flux_analysis/deletion_worker.py, cobra/flux_analysis/double_deletion.py, cobra/manipulation/delete.py, cobra/test/flux_analysis.py
The following changes are made:
- Errors while performing double deletions no longer silently result in 0 values.
- No longer solve a linear program when all reactions removed carry no flux in the optimal solution
- Compiling gene_reaction_rule strings results in faster determination of deleted reactions upon gene knockout.
=> Further speedups and improvements to double deletions

cobra/io/sbml.py
SBML requires that an irreversible rection never be negative. However,
cobrapy's definition of reversibility is more consistent with the
biochemical definition that flux flows both ways. Therefore, set the
SBML reversibility flag when writing out a file by using the criteria of
lower_bound < 0 instead of the Reaction.reversibility property.
This fixes #114.
=> Follow SBML Rerversibility tag guidelines

cobra/io/sbml.py
The unspecific catch in
try:
rule = reaction_note_dict['GENE ASSOCIATION'][0].encode('ascii')
if rule.startswith("&quot;") and rule.endswith("&quot;"):
rule = rule[6:-6]
reaction.gene_reaction_rule = str(rule)
except:
warn("gene_reaction_rule is not ascii compliant")
hid the problem that `str.encode` returns byte in python3 letting
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
go silent.
I reorganized the code a little and made the exception catch `UnicodeEncodeError` (is that what it should catch?) specifically to avoid further problems.
=> Fix python3 specific issue in create_cobra_model_from_sbml_file.

cobra/core/Metabolite.py
Correct a small bug in remove_from_model in core/Metabolite.py when method == "destructive'.
=> Correct bug in remove_from_model in Metabolite.py

cobra/core/Gene.py, cobra/core/Model.py, cobra/core/Object.py, cobra/core/Species.py, cobra/io/json.py, cobra/io/mat.py, cobra/io/sbml.py, cobra/io/sbml3.py, documentation_builder/io.ipynb
This is more consistent (Model.description instead of Model.name was
arbitrary and confusing). This is also more consistent with SBML.
Model.description is still available as a property for compatibility
reasons, but it will raise a warning when accessed.
Some deprecated methods for core classes were also finally removed.
The I/O has been updated to account for the description attribute being
replaced by name.
This fixes #175
=> core element cleanup - all have id and name

cobra/test/__init__.py
This is necessary to inform the operating system whether or not the
tests succeeded.
=> Pass test exit status to the system

cobra/io/sbml.py
To fully incorporate cobrapy into JWS Online (jjj.bio.vu.nl) we need to be able to access the libsbml document object generated by cobrapy (specifically the toSBML() function). Thus, we have split the write_cobra_model_to_sbml_file() function in io/sbml.py into 2 functions, one which simply returns the libsbml document, the other which actually writes to a file.
=> split write_cobra_model_to_sbml_file() into two functions

cobra/io/mat.py, cobra/io/sbml3.py, cobra/test/io_tests.py
This tests for the bug reported in #187 for all I/O formats. It also
includes a fix for the mat file format.
=> test saving empty models and fix for mat

cobra/solvers/glpk_solver.py, cobra/solvers/gurobi_solver.py
izip is no longer present in python versions >3 as zip now has the same functionality and therefore leads to an ImportError for those versions.
=> Import izip from itertools for older python versions

cobra/__init__.py, cobra/design/__init__.py, cobra/design/design_algorithms.py, cobra/manipulation/__init__.py, cobra/manipulation/modify.py, cobra/test/__init__.py, cobra/test/design.py, cobra/test/manipulation.py, setup.py
Adds an OptKnock implementation in `cobra.design`.
To create OptKnock, this also includes:
- A general function for taking the dual: `cobra.design.dual_problem()`
- A function for converting a model to the canonical form: `cobra.manipulation.canonical_form()`.
NOTE:  I have only tested this in Python 2.7 with Gurobi (but code runs in Python 3.5). ~~MIPs did not solve with GLPK.~~ EDIT: Decreased integer tolerance to 1e-9 and MIPs solve with GLPK. Maybe this should be the default value in cglpk.pyx.
=> OptKnock and related functions

cobra/solvers/cplex_solver.py
Okay that one should be good now.
Before:
```
======================================================================
ERROR: test_quadratic (cobra.test.solvers.cplexTester)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/cdiener/code/cobrapy/cobra/test/solvers.py", line 243, in test_quadratic
solver.set_quadratic_objective(lp, quadratic_obj)
File "/home/cdiener/code/cobrapy/cobra/solvers/cplex_solver.py", line 244, in set_quadratic_objective
if lp.parameters.read.qpnonzeros < nnz:
TypeError: unorderable types: NumParameter() < int()
======================================================================
ERROR: test_single_gene_deletion (cobra.test.flux_analysis.TestCobraFluxAnalysis) …
```
=> Fixes a problem with cplex 12.6

.travis.yml, cobra/core/Metabolite.py, cobra/core/Model.py, cobra/core/Reaction.py, cobra/flux_analysis/summary.py, cobra/test/flux_analysis.py, documentation_builder/simulating.ipynb
This PR addresses #223, i.e., adding summary methods to model and metabolite objects.
The summary code is sadly quite messy, but there isn't a great way to pretty-print objects without adding yet another dependency.
I also had to change the Reaction.build_reaction_string method slightly in order to make sure it is deterministic for testing purposes.
=> Adding summary methods

cobra/flux_analysis/parsimonious.py, cobra/solvers/coin.py, cobra/test/flux_analysis.py
From my experience, there's very few times when I wouldn't prefer a parsimonious FBA solution, especially when the computational cost is just one additional LP solve. With the current implementation, however, it can be tedious to use the existing pFBA implementation.
These edits allow users to simply call:
```python
>>> model.optimize(minimize_absolute_flux=1.0)
<Solution 0.87 at 0x1190ed810>
```
to get a parsimonious FBA solution. Additionally, it borrows the concept from flux variability analysis of the fraction of optimum parameter,where passing a value of less than one will find the minimum absolute solution within a given fraction of the optimum.
Sadly If runtime imports are discouraged, this PR may also run into some troubles.
=> Updates to cobra.flux_analysis.parsimonious

documentation_builder/simulating.ipynb
Previously, the summary calls were made on a solution object that was
optimized for ATP maintenance, while the current objective was for
biomass optimization. Addresses #238
=> Fixing summary calls in simulating.ipynb

cobra/solvers/cglpk.pyx
There was a premature return statement that did not clean up the mallocs.
=> Fix for memory leak in cglpk change_coefficient

cobra/test/flux_analysis.py
Even though it was more elegant, the previous test mixed test cases for
the fba and moma single gene deletion. Those cases are now split up into
two distinct test cases to make debugging easier.
=> Split up single_gene_deletion tests

cobra/solvers/gurobi_solver.py
Now sets "verbose" first. Should I also check for "output_verbosity" which is currently not set in the default parameters (and which are the only ones relevant for create_problem)?
=> Repair verbosity for Gurobi 6.5 (fix for #248)

setup.py
The new summary functions use `sort_values` which requires pandas>=0.17. This pull request adds that requirement to setup.py. Also see the mailing list where that problem was first reported.
=> Set version requirement for pandas.

setup.py
This patch ensures a stable ordering for the list of dependencies generated
in setup.py.
=> make the build reproducible

cobra/core/Model.py, cobra/test/unit_tests.py
This commit allows Model.add_reactions to accept a generator input. Also
changes a unittest to pass a generator rather than an equivalent list.
=> Allow add_reactions to accept a generator

cobra/flux_analysis/summary.py
Perhaps in a recent pandas update, Series.to_string includes the name of
the series in the output. As a result:
```
>>> model.summary(fva=.95)
IN FLUXES                     OUT FLUXES                    OBJECTIVES          
met                           met                           EX_biomass         0.319
xyl_e    -9.32 ± 0.18         h_e        29.12 ± 3.97                           
succ_e      5.94 ± 2.47                           
atpm        5.07 ± 0.37        
```
This commit adds the 'header=False' option to suppress this.
=> Fixing string output in model.summary FVA method

cobra/flux_analysis/parsimonious.py
This is a single-line change to optimize_minimal_flux to revert the
model to a irreverisble form before throwing a ValueError. Since these
operate in-place, the model would otherwise be changed after an erroneous
pFBA call.
=> Parsimonious fFBA should return consistent model

cobra/core/Metabolite.py
`None or a dictionary` was probably intended be put in as the documentation for `Model.compartements`.
=> doc: clarify Metabolite docstring regarding compartment arg

cobra/flux_analysis/phenotype_phase_plane.py
give same warning w/w/o palettable if the number of segments is too
large for picking good colors
=> fix #255 common warnings w/o palettable

cobra/flux_analysis/summary.py
This fix resolves #267, in which models that do not conform to the
standard boundary reaction format would cause the `model_summary` method
to fail. Now the summary method will print the ID of the first
metabolite and raise a warning if a boundary reaction exchanges more
than one species.
=> WIP: Fix to model summary methods

.travis.yml, cobra/core/Metabolite.py, cobra/core/Model.py, cobra/flux_analysis/summary.py, cobra/test/flux_analysis.py, setup.py
Here's a possible update to the summary methods. This PR should address the issues raised in #240, #266, (and possibly some new ones introduced in #268).
The output has changed slightly, here's a demo of the new methods:
```python
from cobra.test import create_test_model
model = create_test_model('textbook')
model.optimize()
model.summary()
```
IN FLUXES        OUT FLUXES    OBJECTIVES
---------------  ------------  ----------------------
o2_e      21.8   h2o_e  29.2   Biomass_Ecol...  0.874
glc__D_e  10     co2_e  22.8
nh4_e      4.77  h_e    17.5
pi_e       3.21
Outputs are sorted first by flux value, then by metabolite ID. It should now handle odd model formats, i.e., 
```python
import cobra
model = cobra.io.read_sbml_model('cemet.xml')
model.optimize()
model.summary()
```
IN FLUXES …
=> Rewrite of summary methods

cobra/design/design_algorithms.py
This PR will hopefully fix the failing build on master (and inhereted failed builds on more recent PRs)
=> Fix long-lines issue in design_algorithms.py

cobra/core/Reaction.py, cobra/test/unit_tests.py
This PR adds a `bounds` attribute to `cobra.Reaction`, which allows
bounds to be checked and changed with a single line:
```
model.reactions.PGI.bounds = (0, 1000)
```
```
>>> model.reactions.PGI.bounds
(0, 1000)
```
It's a pretty small change, but it parallels the MATLAB toolbox's `changeRxnBounds` function, which had a `b` option to set both bounds at once.
=> Adding bounds property to reaction

cobra/core/Model.py
can be proper objects so copy by reference of e.g. dictionary `notes`
leads to unexpected behaviour as shown in #272
=> make copies of attributes in reaction

cobra/flux_analysis/variability.py
The FVA in cobrapy alternated between optimizing via minimum and maximum, but the minimum solutions tend to be closer to each other than to the maximum solutions and vice versa. Thus, a better recycling strategy for the solution basis is to minimize all reactions first followed by maximizing them. This is also the algorithm described in the original publication.
Recon 2.2, more than 7500 reactions
```python
from cobra.flux_analysis import flux_variability_analysis
%time va = flux_variability_analysis(recon2)
%time va = flux_variability_analysis(recon2, solver="cplex")
%time va = flux_variability_analysis(recon2, solver="gurobi")
```
Old:
```
cglpk:
CPU times: user 2min 5s, sys: 4 ms, total: 2min 5s
Wall time: 2min 5s
cplex:
CPU times: user 59.4 s, sys: 4 ms, total: 59.4 s
Wall time: 59.4 …
```
=> Make FVA a bit faster.

cobra/core/ArrayBasedModel.py, cobra/test/unit_tests.py
See https://groups.google.com/forum/#!topic/cobra-pie/-Yfx7atjII8
This was a fun one.
Python 3 calls only `__setitem__` and not `__setslice__` as Python 2
and there was an error in the LinkedArray class in `__setitem__`
where it would assign all the values to each attribute in place
of assigning each value to the correct attribute.
Also added a unit test so that behavior is checked in the future and removed an 
unused assignment in the unit tests detected by Flake8.
=> Fixed a bug in ArrayBasedModel bounds setting in Python 3

documentation_builder/conf.py
Quick fix to allow sphinx to access the `flux_analysis.summary` code, currently failing on RTD with:
```python
/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/checkouts/latest/documentation_builder/cobra.flux_analysis.rst:90: WARNING: autodoc: failed to import module 'cobra.flux_analysis.summary'; the following exception was raised:
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/envs/latest/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
__import__(self.modname)
File "/home/docs/checkouts/readthedocs.org/user_builds/cobrapy/checkouts/latest/cobra/flux_analysis/summary.py", line 5, in <module>
from tabulate import tabulate
ImportError: No module named 'tabulate'
```
Assuming this should head to …
=> adding tabulate to the list of mock imports

cobra/core/DictList.py, cobra/core/Model.py, cobra/test/test_dictlist.py, cobra/test/test_model.py
model.notes and model.annotatation object were only copied by reference
which is unintuitive, let's copy those
querying dictlist with a unicode string triggered bug, use six
=> fix: model copy and dict search

cobra/test/test_solver_model.py
`LazySolution` uses the current time stamp to judge whether a solution has changed. On windows `time.time` has lower resoultion than on Linux (officially 1/60 of a second). If resolving takes less than the solution gets the same timestamp. Introducing a sleep period > 1/60 s fixes the test, however for the future we might not want to rely on the time stamp for that. Maybe one could hash the solution and compare hashes rather than timestamps.
=> Fix for failing test on Windows

appveyor.yml
This will run tests with a conda install including numpy and scipy
before creating the wheels as before.
- uses fast-finish so the build fails if the conda tests fail
- Conda is only used for running tests and never to generate
wheels
- include python-libsbml in installation (has windows wheels now)
- `install.ps1` is not necessary anymore with appveyor
- the six.py download did not do anything
- some refactoring due to conda
=> Add conda to build matrix, some small fixes.

cobra/config.py, cobra/core/Model.py, cobra/test/test_solver_model.py, cobra/test/test_solver_utils.py, cobra/util/__init__.py, cobra/util/solver.py
This is a proposal to pave the way for the optlang port of `flux_analysis.py`. The functions defined in `cobra.util.solver` help to temporarily add or remove variables and constraints to the solver. It also includes helpers to extract all available solver interfaces from `optlang`.
This implied some minor changes in `cobra.Model` in setting `Model.solver` and `Model.optimize`. 
The "solver" keyword is now respected in `Model.optimize` but requires a "optlang-" prefix for the optlang solvers.
=> Add helper functions for optlang solvers that work with new context

cobra/core/Solution.py
This might have been an oversight? I prefer knowing I have a 'Solution' object from the __repr__ methods. It seems to be the only remaining __repr_html__ method in cobrapy.
=> removing __repr_html__ from Solution

cobra/io/mat.py
ID setting is already fixed in `devel-2`. This addresses the loading of matlab models with multiple IDs.
Fixes #342 .
=> Fix for multiple IDs in Matlab models

cobra/io/sbml.py
parsing legacy sbml, underscores are dropped for keys, but were then
added back again to reactions notes dict.
=> fix: avoid duplicated gene associations, fix #333

cobra/__init__.py, cobra/core/ArrayBasedModel.py, cobra/core/Model.py, cobra/core/__init__.py, cobra/flux_analysis/sampling.py, cobra/io/mat.py, cobra/test/conftest.py, cobra/test/test_model.py, cobra/util/__init__.py, cobra/util/array.py
Deprecates ArrayBasedModel in favor of separate functions in
cobra.util.array. Still will likely need to implement similar functions
to get bounds arrays for cobra.io.mat
Would close #330
=> Deprecate ArrayBasedModel

cobra/core/Model.py, cobra/core/Reaction.py
This simplifies the implementation of `reaction.boundary`, and removes the (imo) duplicated / undocumented `model.exchanges`. 
I would suggest users in the future to get exchange reactions with 
```python
model.reactions.query(lambda x: x.boundary)
```
Thoughts?
=> Cleaning up reaction.boundary

cobra/core/DictList.py, cobra/test/test_manipulation.py, cobra/test/test_util.py
I mentioned this a while back in the gitter, figured it was an easy enough change I'd just put the PR in to ask how other people feel about this.
I personally don't query on 'id' much, I'll usually use the query function to filter the reactions or metabolite list with a lambda function.
```python
>>> model.reactions.query(lambda r: len(r.reactants) > 1)
```
or 
```python
>>> model.metabolites.query(lambda m: m.charge)
```
Having to pass 'None' each time seems like a bit of a strange default behavior. Would anyone's code be significantly broken by a change like this?
=> Changing default query behavior

cobra/core/Model.py
one-liner, this just makes the context managers a bit more pythonic. If you wanted, you could now do something like
```python
with my_model as m:
m.medium = xylose_medium
```
not necessarily recommending it, but its better than returning None.
=> adding return statement to model context

cobra/core/Model.py, cobra/flux_analysis/moma.py, cobra/flux_analysis/single_deletion.py, cobra/test/test_flux_analysis.py, cobra/test/test_solver_model.py
Sorry that this took awhile, there were a few hickups to sort out. Particularly there were quite some bugs in our initial optlang code and also small issues with optlang. Due to this there are also several changes in the Model code as well as tests. Also waiting for a new optlang release since optlang/devel includes a fix that helps our `Solution` class.
Single deletions are now fully working with optlang (FBA and MOMA). The FBA deletions are more or less twice as slow with optlang (see appended text file) whereas MOMA is as fast as before or even a little faster.
The new interfaces are much nicher in terms of customizability. For instance triple+ deletions with MOMA were impossible with the old interface. Now you can just use:
```Python
from cobra.flux_analysis.moma import moma_model …
```
=> Port single deletions to optlang

cobra/flux_analysis/variability.py, cobra/test/test_flux_analysis.py, cobra/util/solver.py
PR to add optlang to FVA. This already includes several micro-optimizations to get decent speed. However, it gets an additional boost from setting coefs like in #368 or #374. The test output for a version that has #374 merged as well can be found [here](https://github.com/opencobra/cobrapy/files/764889/test_output.txt). Basically there is a difference of about 20% (still 5x faster than the cameo version) but profiling shows that this is mostly due to the Python object system...
=> Port FVA to optlang

.travis.yml, appveyor.yml
we are troubled by spurious crashses on mac and it's stalling
development so, for now on devel-2
- no mac builds
- no py 3.4
- only build master, devel, devel-2 and pr's to those
=> skip mac and 3.4

cobra/test/test_solver_utils.py, cobra/util/solver.py
Removes unsupported/incomplete solver implementations in optlang from `cobra.util.solver.get_solver_name`.
Should fix #408.
=> Revise solver lists for optlang

cobra/test/test_solver_model.py, cobra/util/solver.py
This fixes variables so objectives are transferible between models. Also some linting of docstrings.
Before (current devel-2):
```Python
In [1]: from cobra.test import create_test_model
In [2]: import cobra
In [3]: mod = create_test_model("textbook")
In [4]: mod2 = cobra.Model("test")
In [5]: mod2.add_reactions(mod.reactions)
In [6]: mod2.objective = mod.objective
In [7]: mod.objective.expression
Out[7]: 0
In [8]: mod2.objective.expression
Out[8]: 0
In [9]: mod.optimize()
Out[9]: <Solution 0 at 0x7f56f3b4e4e0>
In [10]: mod2.optimize()
Out[10]: <Solution 0 at 0x7f56f4e00b70>
```
No error, but breaks both objectives at once :sob:
After:
```Python
In [1]: from cobra.test import create_test_model
In [2]: import cobra
In [3]: mod = create_test_model("textbook")
In [4]: mod2 = …
```
=> Make objectives transferible

.travis.yml
Basically enable AppVeyor like behavior. It should speed up testing and the Mac tests are stable now. So I think it's worth using.
=> make travis stop testing after first failure

cobra/core/model.py, cobra/flux_analysis/__init__.py, cobra/flux_analysis/loopless.py, cobra/flux_analysis/sampling.py, cobra/flux_analysis/variability.py, cobra/test/test_flux_analysis.py, cobra/util/array.py, cobra/util/solver.py
Up to now only implements the original method from Schellenberger. First time the optlang interface really shines. I could basically implement the original method as is. This requires less constraints than the prior version in cobrapy and brings a speed up (twice as fast).
As expected *a posteriori* methods are faster. For FVA the loopless version is still slower than the non-loopless one for large problems (kind of expected). However it is much faster than using `add_loopless` or `construct_loopless_model` followed by calling "normal" FVA. Faster meaning 2 seconds vs 2 minutes for textbook and a much larger gap (~1000x) for ecoli.
This one I am still not sure about. So fire away with your comments
A priori:
```Python
with model:
add_loopless(model)
model.optimize() …
```
=> Loopless solutions for optlang [fix #385]

cobra/core/model.py, cobra/util/solver.py
Checking the instance for Objective should be done with `optlang.interface.Objective` and not `model.solver.interface.Objective`. This introduced the following bug which is fixed by this PR:
```Python
In [1]: from cobra.test import create_test_model
In [2]: mod = create_test_model("textbook")
In [3]: o = mod.objective
In [4]: mod.solver = "cplex"
In [5]: mod.objective = o
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-a1035cc6dd94> in <module>()
----> 1 mod.objective = o
/home/cdiener/code/cobrapy/cobra/core/model.py in objective(self, value)
646             value = self.solver.interface.Objective(value, sloppy=False)
647         if not isinstance(value, (dict, …
```
=> Fix instance checking for Objective

cobra/core/dictlist.py, cobra/core/metabolite.py, cobra/core/model.py, cobra/core/reaction.py, cobra/test/test_model.py, cobra/test/test_solver_model.py, cobra/test/test_util.py, cobra/util/solver.py
Got some decent progress.. 
Still todo:
definitely running into the issue of wanting to call other context-managed methods, but not wanting to trigger the issue seen in #393...
@cdiener, I'll probably ask how you do those benchmarks 😄 , we should also make sure we're not torpedoing performance.
=> Context management for Reactions and Metabolites [fix #389]

cobra/io/__init__.py, cobra/io/mat.py, cobra/io/sbml.py, cobra/io/sbml3.py, cobra/test/test_io.py
warnings makes the package look broken even though the lacking functionality is normal and not a concern unless the affected features are actually needed.
Let's raises errors when relevant.
=> fix: don't throw warnings on import

cobra/core/metabolite.py, cobra/core/model.py, cobra/core/reaction.py, cobra/flux_analysis/loopless.py, cobra/flux_analysis/moma.py, cobra/flux_analysis/parsimonious.py, cobra/flux_analysis/single_deletion.py, cobra/flux_analysis/variability.py, cobra/test/test_flux_analysis.py, cobra/test/test_model.py, cobra/test/test_solver_model.py, cobra/test/test_solver_utils.py, cobra/util/solver.py
Whilst updating the notebooks I find the `add_to_solver` utility to be confusing because while we have some (currently unavoidable) convolution between the `Model` and the `Model.solver`, it doesn't feel necessary to explain this to the casual user, and so I would like a `Model.add_constraint_or_variable` (long name though..) as a wrapper to `add_to_solver`.
=> feat: add constraint or variable

cobra/core/arraybasedmodel.py, cobra/core/model.py, cobra/flux_analysis/loopless.py, cobra/test/test_model.py
so let's keep the tests there and fix module renaming mistake
=> fix: array model is deprecated but not defunct - remove model.S

cobra/core/model.py, cobra/flux_analysis/loopless.py, cobra/flux_analysis/sampling.py, cobra/io/mat.py, cobra/test/test_model.py, cobra/util/array.py, release-notes/0.6.0.md
Renames `create_stochiometric_array` to `create_stoichiometric_matrix`, as suggested in #442.
Also, I wasn't paying too close attention to #417, was this really the behavior we want for pandas DataFrames? I would assume that the dataframe returned should be consistent with the other returned values, and have metabolites and rows and reactions as columns.
This PR also implements that change, such that the dataframe return will look like
```
ACALD  ACALDt  ACKr  ACONTa  ACONTb  ACt2r  ADK1  AKGDH  AKGt2r  \
13dpg_c    0.0     0.0   0.0     0.0     0.0    0.0   0.0    0.0     0.0
2pg_c      0.0     0.0   0.0     0.0     0.0    0.0   0.0    0.0     0.0
3pg_c      0.0     0.0   0.0     0.0     0.0    0.0   0.0    0.0     0.0
6pgc_c     0.0     0.0   0.0     0.0     0.0    0.0   0.0    0.0 …
```
=> Some changes to stoichiometric matrix

CONTRIBUTING.rst, develop-requirements.txt
* move pymatbridge out of develop-requirements.txt since it's a fringe case
I could not reproduce the installation problem mentioned in #447 but since hardly anyone develops for the Matlab interface I separated it and put it into the contribution guide.
=> clarify contribution guide [fix #447]

cobra/core/model.py, cobra/test/test_io.py
Contexts cannot (and shouldn't) be saved, but one may want to save a
model object that has a context (e.g. when using multiprocessing.) This 
was not possible as partial functions cannot be pickled. Fix this by deleting 
the context in model's `__getstate__`. Adjust the IO tests to write the model 
within a context.
Pickling and unpickling a model does not touch the model's own context, 
only the saved copy.
=> fix: enable pickling an model with context

cobra/core/model.py, cobra/core/reaction.py, cobra/test/test_model.py
With model as context, `reaction.add_metabolites` would make an
addition of a partial call to `reaction.subtract_metabolites`, which in
turn called `reaction.add_metabolites` thus adding the revert itself back
to the history stack. Avoid this by adding a flag to avoid this addition
from happening. Shame on the ugly extra parameter but saw no good alternatives as the `reaction.add_metabolites` function is quite complex.
Also add small performance boost to make
`model.add_metabolites` on empty list a noop (can happen fairly often when
manipulating many reactions).
=> fix: add metabolites in nested contexts

cobra/core/solution.py, cobra/test/test_flux_analysis.py
milp don't have reduced costs / shadow prices and cplex throws error
when accessing these attributes. Use ugly catch-all to work-around, to be fixed with better errors from optlang
=> fix: catch cplex error for milp (#467)

cobra/core/solution.py, cobra/exceptions.py, cobra/flux_analysis/phenotype_phase_plane.py, cobra/flux_analysis/single_deletion.py, cobra/flux_analysis/variability.py, cobra/test/test_flux_analysis.py, cobra/util/solver.py
The pattern of checking if solver.status != 'optimal' is not and then
raise appropriate exception started to appear in a number of places -
let's have a function for that.
Also tidy up the use of optlang string constants.
=> feat: assert solver status optimal

cobra/core/dictlist.py, cobra/core/model.py, cobra/test/test_util.py
KeyError is more sensible when a missing key than ValueError. Let
property setter convert where appropriate
=> refactor: return KeyError from dictlist.get_by_any

cobra/io/mat.py
Fixes #486.
```bash
python3 -c "import cobra; m = cobra.io.load_matlab_model('iCHOv1.mat'); print(cobra.__version__, m.id)"
0.6.0a4 iCHOv1
```
This might need to get pulled into master as well.
=> Fix for truncated matlab model names.

.gitignore, cobra/flux_analysis/variability.py, cobra/test/test_flux_analysis.py
Solver should be set to the determined `solver_interface`, not the
original argument.
=> fix: find_blocked_reactions solver set bug

cobra/test/conftest.py, cobra/test/test_solver_model.py
Use a session scoped fixture to load the textbook model and a function scoped fixture that creates copies from it. Locally this cuts down the time for all tests by 10 s.
Also had to fix on order dependent test.
=> Increase testing speed

INSTALL.rst, cobra/test/__init__.py, cobra/test/conftest.py
Previously, the `small_model` fixture was not found.
=> make test_all work with Python 2.7

cobra/core/model.py, cobra/flux_analysis/__init__.py, cobra/flux_analysis/gapfilling.py, cobra/test/conftest.py, cobra/test/test_flux_analysis.py, cobra/test/test_model.py, cobra/util/solver.py, cobra/util/util.py, documentation_builder/gapfilling.ipynb, documentation_builder/index.rst, release-notes/0.6.0.md
Suggested re-factor of the gapfilling algorithms. Is the api okay? The reactions are no longer split in forward and reverse, does that make it less useful?
~~Also, sadly this implementation still has a serious bug that I searched too long for and would be happy for hints: the old tests pass but the gapfilling.ipynb doesn't since for some reason the solver ignores the switch constraints allowing flux through reactions that aren't switched on.~~
=> feat: gapfilling with optlang (fix #383)

cobra/core/reaction.py, cobra/test/test_model.py
Previously using `reaction.add_metabolites(*args, combine=False)` in a model context would result in the wrong reaction being returned.
=> Fixing and adding test for combine kwarg in reaction.add_metabolites

cobra/core/reaction.py, cobra/test/test_util.py, cobra/util/util.py
Return a copy of the metabolites dict instead of a read-only object.
=> refactor: remove `FrozenDict` [fix #502]

cobra/core/model.py, cobra/test/test_solver_model.py
This fixes #506, explicitly adds in a call to `reaction._reset_var_cache` when adding back in the reaction.
=> reset variable cache

cobra/core/model.py, cobra/core/reaction.py, cobra/test/test_solver_model.py, release-notes/0.6.2.md
This should close the remaining issue in #506.
Ultimately I don't think the old behavior in reaction.remove_from_model / reaction.delete really make sense if we're trying to get the new context systems to work. They seem to be shortcut methods to avoid copying a reaction object, but if a reaction is inside a context, we'll need to keep a copy around in order to restore it quickly later.
Is anyone opposed to deprecating `reaction.delete` and keeping `remove_from_model`? That way its parallel to the metabolite case, which only implements `remove_from_model`.
=> deprecating reaction.delete, fixing remove_from_model

cobra/core/reaction.py, cobra/test/test_model.py
Based on an E-mail I received.
**Behavior:** using string keys in `add_metabolites` for a reaction that has not yet been added to a model
**Problem:** Error is not very informative and docstring does not mention the limitations for string keys.
**Fix:** Error message that suggests solution and mentioning the limitation in the docstring.
Also fixes a small problem in the add_reaction benchmark that still used the the `delete` argument in `remove_from_model`.
=> Clarify add_metabolites behavior with string keys

setup.cfg
Adds some options for pydocstyle that:
1. use the numpy docstyle standard
2. ignore tests since those do not require docstrings
=> Add some pydocstyle options to `setup.cfg`

cobra/flux_analysis/sampling.py
Sorry for the delay. Took me quite a while to figure out how to manage class attributes in shared memory with `multiprocessing.Pool`. This PR moves all of those to shared memory so additional process in the OptGPSampler do not duplicate those anymore. This has the following effects on `OptGPSampler`:
1. constant memory use independent of the number of processes
2. a bit faster `sample` since the initial memory copy is gone
3. now allows sampling of models with arbitrary size in memory (as long as you have enough RAM for the built matrices), no more 4GB limit due to `pickle` constraints
4. runs much smoother in jupyter now, no idea why though
Also added a section to the docstrings giving the rough order of memory usage.
[Benchmark and convergence analysis] …
=> [sampling] use shared memory for all large arrays

cobra/flux_analysis/summary.py
We've got bigger issues, #520, but this fixes a bug with the FVA handling in summary.
=> Fix FVA in summary calls

cobra/io/dict.py
Having sorted elements in the dictionary representing reactions, metabolites, and genes will affect both JSON and YAML output. Since YAML does not have a built-in way to sort output, this is a necessary change to keep YAML model files consistent.
=> feat: sorted output of model components

cobra/io/mat.py
Throws an error if one attempts to use `model_to_pymatbridge` without having scipy installed. Gave a cryptic error before.
Fixes #517.
=> make it explicit that `model_to_pymatbridge` needs scipy

cobra/flux_analysis/phenotype_phase_plane.py, cobra/test/test_flux_analysis.py, release-notes/next-release.md
Fix bug in production_envelopee occurring for models where the C-source
was formulated as -> x instead of x <-
Also support guessing the C-source reaction.
=> fix: production envelope with unspecified c-source

cobra/core/gene.py, cobra/core/metabolite.py, cobra/core/model.py, cobra/core/reaction.py, cobra/core/solution.py, cobra/test/test_model.py, documentation_builder/faq.ipynb, documentation_builder/getting_started.ipynb, documentation_builder/io.ipynb, documentation_builder/simulating.ipynb, release-notes/next-release.md
When using cobrapy in jupyter, it is useful to have html representations
of common classes. Add for model, reaction, metabolite and solution.
=> feat: add html representations

cobra/core/model.py, cobra/core/solution.py, cobra/test/test_model.py, cobra/util/solver.py, release-notes/next-release.md
Add a feature to replace this
```
model.slim_optimize()
assert_optimal(model)
solution = get_solution(model)
```
with just
```
solution = model.optimize(raise_error=True)
```
and avoid the imports `assert_optimal` and `get_solution` in other packages
=> feat: option to raise error from model.optimize

cobra/core/reaction.py, cobra/flux_analysis/variability.py, cobra/test/test_model.py, release-notes/next-release.md
The string representation should be something nice and readable, not
necessarily the id-property. For this it is safer to use that property
directly. Change the str representation to something more useful than
the reaction id (include the reaction string)
=> refactor: don't use str(reaction) to get reaction.id

cobra/flux_analysis/sampling.py, cobra/test/test_flux_analysis.py
Gives a putative solution for recursion limit errors when using `multiprocessing.Pool`. Apparently arguments can not be a `zip` object. No idea why though...
---
Fixes bugs related to inhomogeneous sampling. Turns out the reprojection strategy was overly complicated and did not work well since it spans very little of the space. As a consequence inhomogeneous sampling often returned identical samples (fixes #558). Using `delta = any_warmup - center` as new direction already works for inhomogeneous problems since `S*(any_warmup - center) = b - b = 0`. This spans the search space much better and gives a much better distribution.   
The sampling problem now stores the nullspace rather than the entire projection (N * N.T) which reduces the memory footprint since it uses memory in the order of …
=> [sampling] fix inhomogeneous sampling and avoid recursion error

cobra/core/solution.py, cobra/test/test_solver_model.py
We talked about this a bit, but `solution.reactions[0].model` points back to the original model that generated the solution.
Do we really need these class members? Other than [this](https://github.com/opencobra/cobrapy/blob/devel/cobra/test/test_solver_model.py#L39) line, everything else seems to pass fine when I remove them.
Thoughts on whether we want this? Let me know if I've missed anything?
=> removing solution links to model

cobra/flux_analysis/sampling.py, cobra/test/test_flux_analysis.py
In rare cases the reprojection will yield bounds violations. If that occurs along with an infeasible sampling center the sampler will fail. This PR now guarantees that `sampler._reproject` always returns a feasible point and will not attempt to reproject already feasible points either (like it did before).
=> [sampling] Fix a reprojection bug

cobra/core/metabolite.py, cobra/core/model.py, cobra/flux_analysis/summary.py, cobra/test/test_flux_analysis.py
This is a PR to fix #520 and de-couple the summary methods from connection via `reaction.flux` to the underlying solver in memory.
`model.summary()` now accepts a kwarg `solution`, which if given will re-use the fluxes from a previous solution. Otherwise puts in a call to `model.optimize()` to get an updated set of fluxes. Speeds don't seem to be affected that much, especially if the solver is able to re-use the solution basis.
=> summary now accepts solution kwarg, resolves if missing

cobra/core/model.py, cobra/io/sbml.py, cobra/test/test_model.py
Underscores in keys for `KEY: value` associations in the notes field are
replaced with spaces so internally use only underscore free keys or
key-values may get repeated in legacy sbml output. Tricky to create
meaningful test for this as the notes field as (mis)using
legacy/incomplete sbml specification for sake of backwards
compatibility.
Also include check to not add Metabolite's with missing id's as causes confusing errors. Found this when trying the model in the original #333
=> fix: avoid adding extra notes in legacy sbml

cobra/core/gene.py, cobra/core/metabolite.py, cobra/core/model.py, cobra/core/reaction.py, cobra/core/solution.py, cobra/flux_analysis/summary.py, cobra/util/util.py
This PR uses the short function previously in `cobra.flux_analysis.summary` to truncate overly long strings in the repr_html output. Closes #577 
Here's a preview:
Do we want to be even more aggressive with the truncation? less aggressive? There's definitely a balance between not blasting the whole screen and still displaying useful information for larger models.
=> Truncate long `__repr_html__` outputs

cobra/core/model.py, cobra/flux_analysis/phenotype_phase_plane.py, cobra/test/test_flux_analysis.py
fix #582 
So far this PR re-organizes the code for `production_envelope` a little bit and catches the potential `ZeroDivisionError` in `mass_yield`. However, I suggest the following further changes which is why I marked this PR as WIP.
1. Allow specification of more than one carbon source.
2. Transform the resulting data frame into wide format (the way it's done in cameo) meaning that maximum and minimum are separate columns.
3. Use the configured solver threshold to convert below threshold values to zero.
=> refactor: transform production envelope to wide format with multiple carbon sources

cobra/flux_analysis/summary.py, cobra/test/test_flux_analysis.py
Previously `model.optimize` could get passed a list of reactions in which one reaction was duplicated. This PR fixes #593 by making sure duplicate reactions are dropped prior to calling `model.optimize`.
=> Quick fix for summary methods with exchange objective

cobra/core/reaction.py, cobra/test/test_model.py
Are we still supporting these overloaded methods? If we are, this is a pretty basic change that essentially lets you `sum` an iterable of reactions.
Python's `sum` starts with a 0, and then adds each element in turn. So previously this would fail with
```python
>>> sum(model.metabolites.etoh_c.reactions)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'int' and 'Reaction'
```
This PR
1) allows an `__radd__` function and
2) explicitly allows `reaction + 0`
So now you can 
```python
>>> sum(model.metabolites.etoh_c.reactions).reaction
'etoh_e + h_e + nad_c <=> acald_c + 2.0 h_c + nadh_c'
```
=> adding reaction `__radd__`

appveyor.yml
* Remove commented lines that haven't been used in a long time.
This PR prevents AppVeyor from leaking the PyPi password in case of errors with twine. In future, storing the password in a `.pypirc` file should be considered.
=> fix: hide the output of the twine command

.travis.yml, scripts/prepare_notes.sh
Upon a tagged Travis will also create a GitHub release. For now the release description is simply a link to our markdown notes because the Travis deploy script badly escapes the string.
=> feat: auto release to GitHub

cobra/core/model.py, cobra/test/test_solver_model.py
Previously, existing reactions were filtered out but still added to the
whole `model.reactions` list. This was generating `ValueError`s although
the method promised to just ignore duplicates.
Basically, the previous lines 536-537 were buggy since existing was a normal `list` and not a `DictList` thus the membership test was not working.
=> fix: avoid adding duplicate reactions

cobra/core/model.py, cobra/core/reaction.py, cobra/flux_analysis/gapfilling.py, cobra/flux_analysis/loopless.py, cobra/flux_analysis/moma.py, cobra/flux_analysis/parsimonious.py, cobra/flux_analysis/sampling.py, cobra/flux_analysis/variability.py, cobra/io/sbml3.py, cobra/solvers/cglpk.pyx, cobra/solvers/cplex_solver.py, cobra/solvers/gurobi_solver.py, cobra/test/test_model.py, cobra/test/test_solver_model.py, cobra/util/solver.py, documentation_builder/conf.py, setup.py
Some minor hickups. Mostly changing inputs and avoiding some cases where symengine does not behave exactly like sympy. Major difference is that some expressions may now be appear as `0.0 + 3*var1 + 4*var2` since for symengine `x + y != 0.0 + x + y` (however that is probably going to be changed soon). This does not seem to break anything in cobrapy but required adjusting the test so that expression are simplified before evaluating equality with another expression.
There are pretty nice speed ups, particularly for some cases where there was a lot of sympy usage.
<details>
First column is sympy second is symengine.
```bash
test  time [ms] without-cache  time [ms] without-cache  fraction
1                  test_pfba_benchmark[optlang-cplex]              1853.764206               283.949210 …
```
=> Make cobrapy compatible with symengine

.travis.yml, appveyor.yml, cobra/io/dict.py, cobra/io/json.py, cobra/io/yaml.py, cobra/test/test_io.py, cobra/test/test_io_order.py, setup.py
Currently, the JSON and YAML writers (inheriting from dict) sort the model attributes. This may cause confusion and is unexpected behaviour. This PR aims to improve that situation and starts out with a series of clear test scenarios.
=> feat: sort out the ordering issues with round tripping models

cobra/flux_analysis/loopless.py, cobra/test/test_flux_analysis.py
Removes the requirement of the fixed objective. Now gives the closest objective value without loops as cameo does. This also make loopless FVA a bit faster. Still pretty slow for large models, but the limiting factor here is changing the objective and getting the solution.
=> Several small adjustments to loopless

cobra/util/solver.py
Very small change. The following will now work:
```Python
In [1]: from cobra.test import create_test_model
Loading symengine... This feature is in beta testing. Please report any issues you encounter on http://github.com/biosustain/optlang/issues
In [3]: mod = create_test_model("textbook")
In [4]: mod.solver = "glpk_exact"
In [5]: mod.optimize()
Out[5]: <Solution 0.874 at 0x7f24c2624208>
```
=> Allow underscores in solver names

documentation_builder/phenotype_phase_plane.ipynb
Reverts opencobra/cobrapy#627
Should be merged to `devel` not `master`.
=> Revert "Update phenotype_phase_plane.ipynb"

.travis.yml, appveyor.yml, release-notes/0.10.1.md, setup.py
(@cdiener and @pstjohn I'm not waiting the customary 24 h since this is breaking all our builds. I'm happy to revert the changes later on.)
=> fix: drop and warn Python 3.4

cobra/core/model.py, cobra/test/test_solver_model.py
Some in-progress attempts at fixing `model.remove_reactions` and `model._populate_solver`. Still not working.
Addresses #655
=> attempts to make reversible reaction deletion work

documentation_builder/conf.py
Necessary to mock `'ruamel'` otherwise rtfd barfs.
=> fix: add ruamel back into the mock list

.gitignore, cobra/flux_analysis/deletion.py, cobra/flux_analysis/sampling.py, cobra/flux_analysis/variability.py, cobra/test/test_flux_analysis.py, release-notes/next-release.md
The `find_essential_genes` and reactions functions did not have an argument to set the number of processes thus the underlying functions were always executed with multiprocessing. This PR fixes that. I have (re-)named the argument `num_cpu` everywhere. I found `num_jobs` slightly confusing since it's about the number of processes and not jobs. I chose `num_cpu` since it is closer to `os.` or `multiprocessing.cpu_count` but would be fine with `num_proc`, too.
=> refactor: add or change `num_cpu` argument

cobra/util/solver.py
Optlang returns more solver status than the ones mapped in the current implementation.
To address that problem, we raise a cobrapy specific exception if it is mapped or a OptimizationError.
We include the solver status in the message to provide the user with a cause for failure.
=> Fix: capture all optlang exceptions

documentation_builder/constraints_objectives.ipynb
The efficient way to add a constrain involving many reactions is to build a dict of coefficients first and add the full constraint at once. This adds an example to the documentation.
=> Documenting how to add constrains involving many reactions

cobra/core/reaction.py
Previously calling `model.reactions.rxn1 + model.reactions.rxn2` would cause the metabolites from rxn2 to be added to the new lumped reaction, while the lumped reaction didn't belong to any model.
This ensures that metabolites being added to a reaction belong to the same model, or are duplicated prior to adding.
@cdiener, locally I'm getting an error with the sampling code based on the fixed seed. Any idea why that might be? Should I just change the test to reflect the new value?
```python
def test_fixed_seed(self, model):
s = sample(model, 1, seed=42)
>       assert numpy.allclose(s.TPI[0], 9.12037487)
E       assert False
E        +  where False = <function allclose at 0x1159ace18>(9.002806727659744, 9.12037487)
E        +    where <function allclose at 0x1159ace18> = numpy.allclose …
```
=> Quick edit to reaction.add_metabolites

appveyor.yml, cobra/test/test_solver_model.py, cobra/util/version_info.py
So this is an attempt to repair appveyor. 
I suspect the problem is that conda has not yet updated pip to version 10. So even if you update pip with conda you get pip 9. this triggers a warning from pip to stderr which appveyor interprets as failure (wrongly so).
=> Repair Appveyor

cobra/flux_analysis/summary.py
This generalizes better to models that have a wide range of different flux values.
=> Changes summaries to use a fractional threshold rather than absolute

cobra/flux_analysis/loopless.py
Used the loopless objective as the target flux. Also there was a missing with block which would not reset the exchange fluxes correctly. Some other small fixes that do not actually affect anything but make the method more explicit.
=> Fix a regression bug in loopless FVA

cobra/flux_analysis/deletion.py, cobra/flux_analysis/variability.py, cobra/test/test_flux_analysis.py
* Fix a small bug that required a QP-capable solver even for linear MOMA.
* Allow all relevant functions to accept an external solution to be used as a reference when using MOMA in deletion studies.
=> refactor: allow an external solution for MOMA

benchmarks/objective_benchmark.ipynb, cobra/flux_analysis/gapfilling.py, cobra/flux_analysis/loopless.py, cobra/flux_analysis/moma.py, cobra/flux_analysis/parsimonious.py, cobra/flux_analysis/room.py, cobra/flux_analysis/variability.py, cobra/test/test_flux_analysis.py
This pull request:
* add benchmarks for ROOM
* fix some solver argument usage to test cases
* in most cases makes use of `Objective.set_linear_coefficients`
* brings down the time for `add_moma` and `add_room` for iML1515 from ~5 min to ~6 s
=> refactor: unify objective creation

cobra/flux_analysis/moma.py, cobra/flux_analysis/room.py, cobra/test/test_flux_analysis.py
Aim:
1. This PR addresses the issue of the ROOM sanity check issue with default model. 
2. It also modifies the existing tests just to be close to the aim of the method.
Modifications:
1. The knock-out reaction has been taken as PYK as the paper states it is a better candidate for this purpose. This solves the GLPK solution issue.
2. The assertions have been changed to fit the proper criteria.
3. The ROOM and MOMA methods have been modified so as to make the solution being optional as opposed to the positional (previously).
@Midnighter please review the changes!
=> ROOM sanity check fix

cobra/test/test_flux_analysis.py
Tiny change to get rid of warnings when running the tests with recent pandas versions.
=> remove deprecated pandas function calls from tests

cobra/flux_analysis/geometric.py, cobra/test/test_flux_analysis.py
As the title says. Small changes to fix the MOMA tests and avoid #715 in geometric FBA.
Fixes #715.
=> fix tests for MOMA and make geometric FBA work with cplex and gurobi

cobra/util/solver.py, setup.py
This fixes some smaller issues with the solver utilities.
The only states currently allowed are OPTIMAL and INFEASIBLE (which throws a warning). However, there are many states that also allow returning fluxes (primal values) and are actually less problematic than INFEASIBLE. For larger models there is FEASIBLE, SUBOPTIMAL or NUMERIC which indicate that the solver found a feasible solution but is not sure whether it is really an optimum (it usually is). I think it should at least be possible to obtain the fluxes from those solver states but currently this is prohibited.
optlang has implemented the QP solver for Gurobi since some time now and it seems to work well in my tests (better numerical stability than the cplex one). So I enabled it for the QP problems.
Bumped the optlang version to …
=> Some proposed changes to the solver utilities

documentation_builder/Makefile, documentation_builder/conf.py, documentation_builder/requirements.txt, setup.py
This is a quick fix that restores documentation building. It seems Sphinx, apidoc, and readthedocs have gone through several iterations and our build pipeline should be updated. I will have to do that for memote anyway, so after I learn how to do it properly, I will make another PR here.
=> fix: restore automatic building of documentation

cobra/medium/boundary_types.py, cobra/test/conftest.py, cobra/test/test_medium.py
=> fix: skip determination of boundary types when no boundary rxns exist

.travis.yml, cobra/flux_analysis/gapfilling.py, cobra/test/test_flux_analysis/test_gapfilling.py
bug fix referenced in Pull Request #687 (Gapfill fix to support new metabolites) using latest devel branch
Updated flux_analysis/gapfilling to support gapfill solutions that add metabolites; tests modified to highlight this case. So, if a gapfill solution adds a reaction that contains metabolites not in the original model, corresponding demand or other reactions will also be added to clear the new metabolites. 
Also updated flux_analysis/gapfilling to check if universal model contains exchange reactions. If exchange_reactions = TRUE, the model is only extended by exchange reactions not already in the universal model.
=> Gapfill bugfix

cobra/medium/minimal_medium.py, documentation_builder/media.ipynb
This improves the docs as discussed in #762 and also provides a better clarification for the difference between concentrations and the growth media in cobrapy. Also avoids a pandas deprecation warning.
Fixes #762.
=> Improve docs for growth media and silence pandas warning

cobra/core/model.py, cobra/core/reaction.py, cobra/manipulation/__init__.py, cobra/manipulation/delete.py, cobra/manipulation/modify.py, cobra/manipulation/validate.py, cobra/test/test_core/test_core_reaction.py, cobra/test/test_manipulation.py, tox.ini
Fix #784 
While trying to handle infinite values for bounds, I tripped over the behavior that adjusts both bounds when the lower bound is larger than the upper bound or vice versa. Is this something people use a lot? To me that seems like trying to be too smart for the user's own good.
=> Fix inf bounds

cobra/io/sbml3.py, cobra/test/test_io/test_sbml.py
libsbml will fail parsing the file if the xml declaration is missing,
so make sure it is always included. The declaration is by default
not written unless a non-standard encoding is used[1].
This is only relevant when a file-like stream object is passed to
`read_sbml_model`.
[1] https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.ElementTree.write
=> Write xml declaration in temporary xml file

setup.py
Fix a bug with `pip install cobra[all]` that was reported on the mailing list.
=> chore: fix extras dependencies

cobra/flux_analysis/sampling.py
So GLPK in optlang preserves the order of variables and constraints when pickling but Gurobi does not. This exposed a bug in the variable mapping in the sampler (order was assumed to be the same when copying model).
```python3
Python 3.6.8 |Anaconda custom (64-bit)| (default, Dec 29 2018, 19:04:46)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.3.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: from cobra.test import create_test_model
In [2]: from cobra.flux_analysis.sampling import OptGPSampler
In [3]: mod = create_test_model("textbook")
In [4]: mod.solver = "gurobi"
In [5]: mod.solver
Out[5]: <optlang.gurobi_interface.Model at 0x11a150a90>
In [6]: opt = OptGPSampler(mod, processes=4)
Read LP format model from file …
```
=> Fix sampling in Gurobi

cobra/flux_analysis/geometric.py
Since the counter is incremented at the end of the loop, the check needs to be changed. Otherwise there will be `max_tries + 1` iterations.
=> fix: limit the number of loops correctly

cobra/core/group.py, cobra/core/model.py, cobra/test/test_core/test_model.py
Also add a test case and the dunder len method to `Group`.
=> fix: remove bug in copying models with groups

cobra/flux_analysis/geometric.py, cobra/test/test_flux_analysis/test_geometric.py
Added `processes` to `geometric_fba` signature and exposed the `processes` argument in the underlying `flux_variability_analysis` calls as discussed in #823. 
Previously, the `processes` value was linked solely to the configuration object, which has a default value equal to the number of CPUs on the machine. This change will allow for the user to override the value in the configuration object. The default value is `None`, which mirrors the default value in `flux_variability_analysis`.
=> Added processes to geometric_fba signature.

cobra/core/reaction.py, cobra/test/test_core/test_core_reaction.py
This PR is supposed to fix #858.
=> Set correct flux bounds 

setup.py
This is fixing the SBML issues for now. 
Main issue is that there is a delay between python releases and the availability of wheels.
Pinning the dependencies fixes this. I will update the version when wheels are available.
=> Pinning dependency to fix wheel issues

documentation_builder/conf.py
This now uses the builtin Mock() class rather than a hacked one and only documents the cobra package. Tested this branch on readthedocs and it builds fine with the same settings as the real project: https://cobrapy-cdiener.readthedocs.io/en/latest/
=> Fix mocks and autoapi paths in documentation builder

setup.py, tox.ini
Since libsbml (experimental) is now a permanent dependency, we don't need the sbml extras any longer.
=> chore: remove sbml extras

cobra/io/sbml.py
Hi all, in our application we saw cobrapy logging an error with message "None", in addition to a stacktrace for a _handled_ exception being printed to console. The cause is that `traceback.print_exc()` is assumed to return a string, but it only _prints_ an exception to console and returns nothing.
In this fix, I suggest to use [exception chaining](https://legacy.python.org/dev/peps/pep-3134/) instead of logging. This gives the calling context access to everything needed to investigate the root cause if wanted, and decide whether or not to log events and/or print anything to console.
=> Chain the original SBML exception

cobra/io/sbml.py
Looks like just an oversight. Using a named logger lets callers configure the logger to behave as they want.
=> Log events with module logger, not root logger

cobra/test/test_core/test_model.py, cobra/test/test_core/test_summary/test_metabolite_summary.py
Some tests would currently fail for cplex, gurobi and symengine. For instance here a recent test run from my machine
<details>
```bash
Test session starts (platform: linux, Python 3.7.5, pytest 5.2.1, pytest-sugar 0.9.2)
benchmark: 3.2.2 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/cdiener/code/cobrapy, inifile: setup.cfg, testpaths: cobra/test
plugins: cov-2.6.1, sugar-0.9.2, dash-1.4.1, benchmark-3.2.2, mock-1.10.4
collecting ... 
cobra/test/test_manipulation.py ✓✓✓✓✓✓✓✓✓✓✓                                                                                                                     2% ▎         
cobra/test/test_medium.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓ …
```
=> Make tests compatible with optional dependencies

appveyor.yml, cobra/medium/minimal_medium.py, cobra/test/test_core/test_summary/test_metabolite_summary.py
Similar to FVA this adds a warning and `None` return for cases where the repeated optimization of the same objective with the same model suddenly leads to a non-optimal solution. This is only the case for numerically unstable models so it is hard to add a test for this case since none of the test models included in cobrapy will ever run into this case.
Related to #928
=> Handle repeated infeasible MIP optimization in minimal_medium

setup.py
Python 3.8 was released in late 2019.
Python 2.7 is EOL since January 2020, and 3.4 since March 2019. See https://devguide.python.org/devcycle/#end-of-life-branches. CI test runs on both versions was removed in #939. This also removes them from package metadata.
This change marks removal of support for Python 2. It may deserve a major version bump.
=> Add Python 3.8 and remove EOL version support

cobra/io/sbml.py, cobra/test/test_io/test_model_notes.py, cobra/test/test_io/test_notes.py
Currently, if we add some notes to a cobra_model and write that model to SBML, these notes are not written in the file.
Fixes issue #902 
Inside the method **_model_to_sbml()** which is used convert the _cobra_model_ to _libsbml.SBMLDocument_ object, the conversion of _notes_ for the _cobra_model_ was not done. Only _annotations_ were converted. So the method for conversion of _notes_ of the model is added here.
=> Writing notes for model in SBML file

cobra/core/group.py, cobra/test/test_core/test_group.py
Following the discussion in #923, groups members are now stored in DictLists instead of sets, to keep order in I/O cycles
=> fix: switch group type from set to DictList

cobra/io/sbml.py
I think `SBO:0000626` is more appropiate than `SBO:0000625` for infinity bounds. From the SBO documentation:
* [SBO:0000625](http://www.ebi.ac.uk/sbo/main/SBO:0000625): _"A parameter that limits the upper or lower value that a flux may assume. This parameter may be determined experimentally, or may be the result of theoretical investigation."_
* [SBO:0000626](http://www.ebi.ac.uk/sbo/main/SBO:0000626): _"A value used for flux bound in cases where a precise value, supported experimentally or theoretically, is not available."_
=> fix: SBO terms for infinity bounds

cobra/io/mat.py
New yeast models are provided with 2 letter compartment names.  Currently, the import of Yeast models from Matlab will omit the two-letter compartments.
=> FIX: Allow comparment names with two letters

src/cobra/core/model.py, src/cobra/flux_analysis/moma.py, src/cobra/io/sbml.py, src/cobra/test/test_flux_analysis/conftest.py, src/cobra/test/test_flux_analysis/test_moma.py, src/cobra/test/test_io/test_annotation.py, src/cobra/test/test_io/test_sbml.py, src/cobra/test/test_util/test_solver.py, src/cobra/util/solver.py, tox.ini
This branch adds support for the [OSQP](https://osqp.org) quadratic problem solver through https://github.com/biosustain/optlang/pull/210. This will not be useful until OSQP support is merged into optlang and a release has been made and mostly exists here for testing purposes. 
To test this branch you can create a *new* python or conda environment and install this branch along with the optlang OSQP branch:
```bash
pip install pip install git+https://github.com/cdiener/optlang@feature/osqp
```
If everything works that will give you QP support without a commercial solver.
**Example:**
```python
from cobra.test import create_test_model
from cobra.flux_analysis import pfba, moma
mod = create_test_model("textbook")
wt_sol = pfba(mod)
mod.solver = "osqp"
with mod: 
mod.reactions.PFK.knock_out() …
```
=> Add support for the OSQP solver
