- cobra/io/sbml3.py
- cobra/manipulation/modify.py
- cobra/test/io_tests.py
This can provide some checks to see if an SBML file will load into cobrapy. It doesn't intend to be a full substitute for libsbml validation.
> add function to validate sbml3

- cobra/io/json.py
The defined format changed a few things in a compatible way by marking
some attributes as optional.
This fixes #125 and replaces #170
> create a JSON schema

- cobra/core/Reaction.py
Hello,
I think it would be nice being able to pass the information to the reaction already during initialization as it is already the case for metabolites.
> Provide the possibility to pass all information in initialization

- cobra/external/ppmap.py
- cobra/solvers/cplex_solver_java.py
- cobra/solvers/glpk_solver_java.py
- cobra/solvers/gurobi_solver_java.py
- cobra/topology/reporter_metabolites.py
The changes here consist of using the print function as well
as catching exceptions using "as" rather than commas.
> Improve Python3 compatibility

- cobra/topology/__init__.py
Signed-off-by: Vivek Rai <vivekraiiitkgp@gmail.com>
> Fix import issue in cobra.topology

- cobra/core/ArrayBasedModel.py
- cobra/core/DictList.py
- cobra/core/Formula.py
- cobra/core/Gene.py
- cobra/core/Metabolite.py
- cobra/core/Object.py
- cobra/core/Reaction.py
Signed-off-by: Vivek Rai <vivekraiiitkgp@gmail.com>
> Fix ununsed imports, variable assignments

- .gitignore
- cobra/design/design_algorithms.py
- cobra/flux_analysis/deletion_worker.py
- cobra/flux_analysis/double_deletion.py
- cobra/flux_analysis/essentiality.py
- cobra/flux_analysis/gapfilling.py
- cobra/flux_analysis/loopless.py
- cobra/flux_analysis/parsimonious.py
- cobra/flux_analysis/phenotype_phase_plane.py
- cobra/flux_analysis/reaction.py
- cobra/flux_analysis/summary.py
- cobra/flux_analysis/variability.py
- cobra/topology/__init__.py
- cobra/topology/reporter_metabolites.py
Changes are for `flux_analysis` and `topology` directories. Already done for `core`.
Signed-off-by: Vivek Rai <vivekraiiitkgp@gmail.com>
> Update .gitignore, fix code style, unused imports, possible bugs

- cobra/flux_analysis/summary.py
- cobra/test/flux_analysis.py
This pull request is set up to address points raised in #240.
Currently only the first two points have been addressed.
> Summary method improvements

- cobra/flux_analysis/phenotype_phase_plane.py
avoid 'Fall back to Agg renderer' as suggested here
https://github.com/matplotlib/matplotlib/issues/1852
> fix broken plot on mac osx #265

- CONTRIBUTING.rst
- INSTALL.rst
- develop-requirements.txt
Also updated INSTALL.rst to reference detailed directions in CONTRIBUTING.rst and added a develop-requirements.txt to make it easy to install of the required packages for development. Tested the directions on a Mac.
> Update directions for setting up development environment. 

- cobra/io/sbml3.py
- cobra/test/io_tests.py
This replaces #294 and includes the changes discussed there on top of the repaired CI to have a cleaner history.
> Changes to SBML3 validator.

- .gitignore
- cobra/flux_analysis/parsimonious.py
- cobra/test/conftest.py
- cobra/test/test_flux_analysis.py
- cobra/test/test_model.py
- tox.ini
- use bigger model for meaningful comparisons, isolate benchmarks
- missing check of args failing tests when repeated in optlang
- don't benchmark with tox..
- don't version the benchmarks
> fix: improve tests / correct missing args pfba

- INSTALL.rst
- cobra/test/__init__.py
- develop-requirements.txt
- setup.py
and fail gracefully if not available, fix issue #325
> make pytest an optional dependency

- cobra/flux_analysis/sampling.py
Various fixes related to flux sampling. Resolves issues in #328.
> Fixes to sampling

- .travis.yml
- appveyor.yml
- appveyor/build_glpk.py
- cobra/manipulation/delete.py
- cobra/test/test_manipulation.py
these functions had no tests and used defunct arguments
> fix: broken prune_unused_{metabolite,reactions}

- cobra/io/sbml.py
> [SBML 2] Set charge from notes if not defined elsewhere

- .travis.yml
- cobra/io/sbml.py
- tox.ini
Quick fix, this should let us drop the exclusion for pep8 checks of sbml.py
> pep8 fixes for sbml.py

- appveyor.yml
- config.sh
- also repair the broken appveyor plan where conda clash with setuptools and pytest
> Fix coverage miscalculation - fix #347

- cobra/util/solver.py
suppose not intentional and can cause odd phenomena. correct numpy
docstring syntax
> fix: avoid immutables in defaults

- .travis.yml
- appveyor.yml
- cobra/test/test_solver_model.py
- cobra/util/solver.py
adding 'check_context' kwarg to set_objective, fixes #393
Also refactors if statements as suggested by @cdiener
> Fix for objective setting in nested contexts

- .travis.yml
- appveyor.yml
- cobra/core/dictlist.py
- cobra/core/metabolite.py
- cobra/core/model.py
- cobra/flux_analysis/__init__.py
- cobra/flux_analysis/double_deletion.py
- cobra/flux_analysis/loopless.py
- cobra/flux_analysis/parsimonious.py
- cobra/flux_analysis/sampling.py
- cobra/flux_analysis/single_deletion.py
- cobra/flux_analysis/summary.py
- cobra/flux_analysis/variability.py
- cobra/io/json.py
- cobra/test/test_flux_analysis.py
- cobra/test/test_model.py
- cobra/test/test_solver_model.py
- cobra/test/test_solver_utils.py
- cobra/util/__init__.py
- cobra/util/array.py
- cobra/util/solver.py
- setup.py
- add a `return_frame` argument to pfba, fva, single_x_deletion
- reaction / gene id is in the index but perhaps could think of further standardisation of the columns but also that this will be easier once we start thinking of plotting options (in a different package)
- bit ugly whilst we still work on the updated Solution class
> Feature: data frame as return value [fix #412]

- .gitignore
- cobra/exceptions.py
- cobra/flux_analysis/__init__.py
- cobra/flux_analysis/parsimonious.py
- cobra/flux_analysis/phenotype_phase_plane.py
- cobra/flux_analysis/single_deletion.py
- cobra/test/test_flux_analysis.py
- cobra/util/solver.py
Introduce a function to obtain a data frame with a production envelope
for one or more variable reactions and a given objective, including
carbon and mass yield conversions.
- Only to be merged after the new Solution class is in place
> Feat/production envelope [fix #382]

- cobra/flux_analysis/loopless.py
- cobra/test/test_flux_analysis.py
..or possibly rename to loopless_fluxes
> fix: let loopless solution return a solution

- cobra/core/solution.py
- cobra/test/test_flux_analysis.py
- cobra/util/solver.py
for integer problems reduced costs are not well defined so some toy
models don't get any.
> fix: return solution even when reduced costs undefined

- .travis.yml
- config.sh
- documentation_builder/autodoc.sh
- documentation_builder/getting_started.ipynb
- documentation_builder/index.rst
- missing link to notebook
- use own python-libsbml index to get mac wheels
> fix: missing link in docs / libsbml

- css/styles.css
- index.html
- index.xml
- intro/index.xml
- packages/index.html
- pubs/index.html
- pubs/index.xml
- releases/0.5.11/index.html
- releases/0.6.0a2/index.html
- releases/index.html
- releases/index.xml
- sitemap.xml
- tags/general-modeling/index.html
- tags/index.html
- tags/microbiota/index.html
- tags/strain-design/index.html
- tags/synthetic-biology/index.html
- tags/visualization/index.html
- tags/web-app/index.html
Adds a release section to the webpage. Also updates the list of publications and add some badges to the home page.
> [webpage] updates and added release section

- cobra/io/__init__.py
- cobra/io/json.py
Useful functions outside cobrapy so give public names.
> feat: expose _{to,from}_dict

- index.xml
- packages/index.html
- pubs/index.html
- pubs/index.xml
- releases/0.5/index.html
- releases/0.6_alpha/index.html
- releases/index.html
- releases/index.xml
- sitemap.xml
- releases now have a release type which is indicated on the page
with a small description
- packages are now sorted by the number of Github Stars
- publication dates are now taken from the actual publication date
if available and only from the Pubmed date if not
> [website] Several updates.

- cobra/core/gene.py
- cobra/core/reaction.py
- cobra/test/test_model.py
- documentation_builder/deletions.ipynb
- release-notes/0.6.0.md
As we can knock-out reactions, it is natural to also be able to
knock-out reactions. Knocking a gene marks it as non-functional along
with all reactions which are not functional without that gene.
> feat: knock-out genes

- cobra/core/solution.py
- setup.py
`optlang.Model` now has an `is_integer` attribute which we can use to greatly improve the `get_solution`.
> Clean up the `get_solution` function using new optlang features

- cobra/io/sbml3.py
- cobra/test/test_io.py
The direction of optimization can be specified in sbml3 but was not respected #480
> fix: sbml set objective direction (fixes #480)

- cobra/core/model.py
- cobra/test/conftest.py
- cobra/test/test_model.py
- cobra/util/util.py
- release-notes/0.6.0.md
Add convenient function for rapidly creating an exchange reaction for a
given metabolite
> feat: add_exchange reaction

- index.xml
- packages/index.html
- packages/index.xml
- pubs/index.html
- pubs/index.xml
- sitemap.xml
- tags/algorithms/index.html
- tags/cell-factories/index.html
- tags/community-modeling/index.html
- tags/flux-analysis/index.html
- tags/gapfilling/index.xml
- tags/general-modeling/index.html
- tags/index.html
- tags/mathematical-modeling/index.html
- tags/me-models/index.html
- tags/microbiome/index.html
- tags/microbiome/index.xml
- tags/microbiota/index.html
- tags/microbiota/index.xml
- tags/models/index.html
- tags/models/index.xml
- tags/modelseed/index.html
- tags/modelseed/index.xml
- tags/reconstruction/index.html
- tags/reconstruction/index.xml
- tags/strain-design/index.html
- tags/synthetic-biology/index.html
- tags/visualization/index.html
- tags/web-app/index.html
- tags/web-app/index.xml
> Update Mike's packages and add a publication.

- documentation_builder/conf.py
- setup.py
- update the author and maintainer to reflect the community effort
- debug the sphinx conf after new dependency
> docs: fix author and sphinx docs

- css/styles.css
- index.html
- index.xml
- packages/index.html
- pubs/index.html
- releases/0.5.11/index.html
- releases/0.6.0/index.html
- releases/0.6.1/index.html
- releases/index.html
- releases/index.xml
- sitemap.xml
- tags/algorithms/index.html
- tags/cell-factories/index.html
- tags/community-modeling/index.html
- tags/flux-analysis/index.html
- tags/gapfilling/index.html
- tags/general-modeling/index.html
- tags/index.html
- tags/mathematical-modeling/index.html
- tags/me-models/index.html
- tags/microbiome/index.html
- tags/microbiota/index.html
- tags/models/index.html
- tags/modelseed/index.html
- tags/reconstruction/index.html
- tags/strain-design/index.html
- tags/synthetic-biology/index.html
- tags/visualization/index.html
- tags/web-app/index.html
As discussed in the source repo.
See https://github.com/opencobra/cobrapy-website for details.
[preview](https://opencobra.github.io/cobrapy-website)
> [website] Add recent updates

- cobra/flux_analysis/summary.py
remove internal call to deprecated method
> remove rxn.x call in summary

- cobra/flux_analysis/reaction.py
- cobra/test/test_flux_analysis.py
- release-notes/0.6.3.md
cobra.flux_analysis.reaction needed refactoring after changes in 0.6.0.
Refactor, cleanup and add tests.
Fix #537
> fix: repair broken cobra.flux_analysis.reaction

- cobra/core/model.py
- cobra/core/reaction.py
- cobra/flux_analysis/gapfilling.py
- cobra/flux_analysis/loopless.py
- cobra/flux_analysis/parsimonious.py
- cobra/flux_analysis/phenotype_phase_plane.py
- cobra/flux_analysis/reaction.py
- cobra/flux_analysis/sampling.py
- cobra/flux_analysis/single_deletion.py
- cobra/flux_analysis/variability.py
- cobra/test/test_flux_analysis.py
- cobra/test/test_manipulation.py
- cobra/test/test_model.py
- cobra/test/test_solver_model.py
- cobra/util/solver.py
- documentation_builder/simulating.ipynb
- release-notes/next-release.md
- Introduce new method on Model to do optimization without creating a solution.
- a couple of tests emitted visible warnings during tests, capture them appropriately
- fixes #540
> feat: model.slim_optimize

- cobra/flux_analysis/__init__.py
- cobra/flux_analysis/variability.py
- cobra/test/test_flux_analysis.py
- release-notes/next-release.md
Add convenience functions for getting sets of essential genes and
reactions. Using this in two other packages that both depend on cobrapy
so better move here.
> feat: essential genes and reactions

- cobra/flux_analysis/single_deletion.py
A lot has happened since the optlang transition so the code could be simplified. That module will become pretty slim when removing the old solver interface. 
Instead of returning 0 for infeasible solutions we now return float("nan") since it makes more sense. For instance if you have a lower bound > 0 for a growth rate it might be confusing to see a zero growth rate in the result.
> Update single deletion code

- cobra/flux_analysis/variability.py
Instead of rolling own, use the existing single_x_deletions for
find_essential_{genes,reactions}}
> refactor: use single_x_deletion functions

- cobra/flux_analysis/moma.py
- cobra/flux_analysis/single_deletion.py
- cobra/test/test_flux_analysis.py
- cobra/test/test_solver_utils.py
- cobra/util/solver.py
Adds linear MOMA to `add_moma`.
> Add linear MOMA

- .travis.yml
experiments to get ci on linux working again
> chore: downgrade pytest-ci

- .travis.yml
New release following https://github.com/ionelmc/pytest-benchmark/issues/82
> chore: unpin pytest-benchmark

- appveyor.yml
- cobra/core/model.py
- cobra/test/test_model.py
Let me know if I should make use of this new property in other code in this PR or if we should slowly migrate code whenever/wherever we come across it.
> feat: add revertible property objective_direction [WIP]

- scripts/publish_release.py
Just a typo. The tag can not have spaces :sweat_smile:
> Fix incorrect "<!--more-->" tag in releaser

- cobra/flux_analysis/deletion.py
- cobra/flux_analysis/variability.py
- cobra/test/test_flux_analysis.py
- cobra/test/test_solver_model.py
> refactor: deletions interface; objective value; tests

- documentation_builder/phenotype_phase_plane.ipynb
Originally submitted by @Behoston, messed up by myself.
> fix: update argument name

- cobra/flux_analysis/parsimonious.py
- cobra/flux_analysis/variability.py
- cobra/test/test_flux_analysis.py
- release-notes/next-release.md
The main change is to ensure that the variable that records the value of the old objective has an upper bound when the previous objective was a minimization. Additionally, I used the opportunity to clean up the docstrings a little. I also included a minimal test case plus made a note for the next release.
> refactor: FVA

- cobra/flux_analysis/deletion.py
- cobra/flux_analysis/room.py
- cobra/test/test_flux_analysis.py
Updated version of #679. Separate PRs due to commit conflict issues. Needs performance improvement when using Sympy. Symengine works perfectly.
> Added ROOM with tests from original paper

- cobra/flux_analysis/__init__.py
- cobra/flux_analysis/geometric.py
- cobra/flux_analysis/room.py
- cobra/test/test_flux_analysis.py
- documentation_builder/simulating.ipynb
This PR adds geometric FBA with tests from original paper and also adds documentation in the notebooks. This also resolves #650. Please review the code @Midnighter.
> Added feature geometric FBA

- cobra/flux_analysis/geometric.py
- cobra/flux_analysis/room.py
- cobra/test/test_flux_analysis.py
Uses the default test model now. Also, adds similar assertion checks used in the test suite.
> Fix: ROOM sanity check

- cobra/flux_analysis/__init__.py
- cobra/flux_analysis/deletion.py
- cobra/flux_analysis/moma.py
- cobra/flux_analysis/room.py
- cobra/flux_analysis/variability.py
- cobra/test/test_flux_analysis.py
* Add one off functions for MOMA and ROOM
* Add and reword documentation
* Export MOMA/ROOM to ``flux_analysis`` package
* Remove superfluous ``solution`` argument from essentiality functions
> refactor: add functions, documentation for MOMA/ROOM

- benchmarks/geometric_fba.ipynb
- benchmarks/single_gene_deletion_linear_room.ipynb
- benchmarks/single_gene_deletion_room.ipynb
- cobra/flux_analysis/geometric.py
- cobra/test/test_flux_analysis.py
* Add logging to geometric FBA.
* Skip GLPK for the ROOM benchmark.
> fix: change the benchmark solvers

- cobra/core/metabolite.py
- cobra/core/model.py
- cobra/flux_analysis/summary.py
- cobra/test/test_flux_analysis.py
* Correct a problem with multiple exchanges for one metabolite.
* Enhance printing by giving an option to display names.
* Allow passing in of an FVA solution.
* Many internal changes related to data frame handling.
Still need to adjust the test cases accordingly.
> fix: allow multiple exchanges in summary

- cobra/core/model.py
- cobra/medium/__init__.py
- cobra/medium/boundary_types.py
- cobra/medium/minimal_medium.py
- cobra/test/test_medium.py
- cobra/test/test_model.py
- documentation_builder/index.rst
- documentation_builder/media.ipynb
This extends #589. It implements all changes made there and adds additional detection methods for the boundary type of a reaction (exchange, demand, sink).
I am not sure if the boundary type API is super elegant. So would be good if somebody could take a look.
> Advanced handling of exchanges and growth media

- documentation_builder/constraints_objectives.ipynb
- documentation_builder/media.ipynb
- documentation_builder/solvers.ipynb
Fixes small errors in the documentation.
> Fix documentation

- .travis.yml
- cobra/io/yaml.py
- setup.py
- tox.ini
I updated ruamel.yaml version, changed to the new API.
> fix: update ruamel.yaml

- cobra/core/model.py
- cobra/test/test_model.py
> Update model objective on context exit if removed reaction is a part of the objective function

- cobra/test/test_solver_utils.py
- cobra/util/solver.py
Smaller PR than anticipated since it seems we already implemented allowing other solutions states at some point. 
Now allows getting the intermediate solution if the time limit is reached.
Also adds a test.
Fixes #688.
> Allow getting a solution if time limit reached

- .github/CONTRIBUTING.rst
Added an FAQ section, with the first question and answer pertaining to updating pickles when the model class is modified. Fixes #761
> Update contribution instructions w/ FAQ about pickles

- cobra/__init__.py
- cobra/core/__init__.py
- cobra/core/configuration.py
- cobra/core/model.py
- cobra/core/reaction.py
- cobra/core/singleton.py
- cobra/io/sbml.py
- cobra/io/sbml3.py
- cobra/test/test_core/test_configuration.py
- documentation_builder/configuration.ipynb
- documentation_builder/index.rst
This PR addresses https://github.com/opencobra/cobrapy/issues/741.
- is singleton
- solves setting of default parameters
> feature: Configuration class

- cobra/flux_analysis/variability.py
Some docstring improvements and indexing improvements since I was just looking at the function.
> refactor: use pandas indexing for blocked reactions

- cobra/core/model.py
- cobra/io/sbml3.py
- cobra/manipulation/annotate.py
- cobra/manipulation/validate.py
- cobra/medium/__init__.py
- cobra/medium/boundary_types.py
- cobra/test/data/mini.json
- cobra/test/data/mini.yml
- cobra/test/test_manipulation.py
- cobra/test/test_medium.py
> refactor: make add_boundary arguments more flexible

- cobra/flux_analysis/__init__.py
- cobra/flux_analysis/fastcc.py
- cobra/test/test_flux_analysis/test_fastcc.py
- documentation_builder/consistency.ipynb
- documentation_builder/index.rst
- documentation_builder/simulating.ipynb
This PR adds FASTCC as an option for consistency checking. It also adds documentation regarding consistency checking, describing use of FVA as well as FASTCC.
I had to implement FASTCC as part of FASTCORE, so thought of adding FASTCC to the cobrapy arsenal. I hope it is useful for the users. And, if this doesn't fit here, I would be happy to keep it in driven.
> feature: add FASTCC

- cobra/core/configuration.py
- cobra/core/model.py
- cobra/exceptions.py
- cobra/test/test_core/test_configuration.py
This PR updates the Configuration object by adding ability to set solver tolerances. It also updates the representation of the object.
> update: Configuration

- .travis.yml
- scripts/publish_release.py
I noticed some problems with our deployment pipeline. These configuration changes should improve things quite a bit.
> chore: fix deployment

- cobra/flux_analysis/fastcc.py
- cobra/flux_analysis/helpers.py
- cobra/flux_analysis/loopless.py
- cobra/flux_analysis/phenotype_phase_plane.py
- cobra/flux_analysis/variability.py
- cobra/io/sbml.py
- tox.ini
> update: use model tolerance for functions setting flux thresholds

- cobra/io/sbml.py
- cobra/test/data/annotation.xml
- cobra/test/data/validation.xml
- cobra/test/test_io/test_sbml.py
- setup.py
Another round of bugfixes.
In addition the validation of SBML files is improved now catching parser warnings and errors.
> SBML bugfixes and validation improvements

- appveyor.yml
- tox.ini
> chore: exclude Python 2 from AppVeyor

- cobra/io/sbml.py
Fix #845 and Fix #851 
Correct reporting of invalid SBML ids in error log and reading of models with invalid SBML ids.
> SBML bugfixes

- cobra/sampling/optgp.py
> fixing parameters typo

- cobra/core/reaction.py
> Delete objective_coefficient in reaction.py __init__

- cobra/flux_analysis/fastcc.py
- cobra/test/test_flux_analysis/test_fastcc.py
This PR fixes #806. For now, it still needs some refinement to be in proper shape.
> update: make fastcc iterative

- documentation_builder/conf.py
Adds missing mock imports. Refactor of #874 by @pbordron.
> Fix documentation builder

- cobra/core/metabolite.py
- cobra/core/model.py
- cobra/core/reaction.py
- cobra/core/summary/metabolite_summary.py
- cobra/core/summary/model_summary.py
- cobra/core/summary/reaction_summary.py
- cobra/core/summary/summary.py
- cobra/test/test_core/test_summary/test_metabolite_summary.py
- cobra/test/test_core/test_summary/test_model_summary.py
Okay, re-opening these commits which mainly modify the docstrings and some of the argument passing of the other PR.
> Abstract summary

- cobra/io/yaml.py
- setup.py
> Fix import of YAML for ruamel

- documentation_builder/conf.py
This adds the missing mock module. Hopefully that lets the docs build now.
> Add more mock modules

- cobra/flux_analysis/loopless.py
- cobra/flux_analysis/variability.py
- cobra/test/test_io/test_sbml.py
Addresses #865.
For some models there may exist an optimum for the reference FVA solution but consecutive optimizations may not find the optimum again due to numerical issues, leading to infeasible solutions in FVA loops. This adds code to handle this gracefully. 
I can't really add a test for that since none of our test models are this unstable.
> Handle numerical problems gracefully in FVA

- setup.py
Refs https://github.com/sbmlteam/python-libsbml/issues/17
> Depend on a python-libsbml that supports Py 3.8

- .github/CODE_OF_CONDUCT.md
- README.rst
@opencobra/cobrapy-core we need to decide on a contact e-mail address where concerns can be reported.
> WIP: Add a code of conduct
